# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License
version: "3"
services:
  openpaimarketplace_rest_server:
    container_name: openpaimarketplace_rest_server
    image: openpai/pai-marketplace-restserver:v1.4.1
    restart: always
    depends_on:
      - postgres
    environment:
      DB_USERNAME: user
      DATABASE: marketplace
      DB_PASSWORD: postgre
      DB_HOST: postgres
      DB_PORT: 5432
      NODE_ENV: production
      PORT: 9293
    ports:
      - "9293:9293"
    working_dir: /usr/src/app/openpaimarketplace/rest_server
    command: ["npm", "start"]

  postgres:
    container_name: postgres_for_openpaimarketplace_rest_server
    image: postgres:12.0
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: marketplace
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  openpaimarketplace_webportal_plugin:
    container_name: openpaimarketplace_webportal_plugin
    image: openpai/pai-marketplace-webportal:v1.4.1
    restart: always
    environment:
      MARKETPLACE_API_URL: https://MasterIP:8443/openpaimarketplace_rest_server
    ports:
      - "9292:9292"

  nginx:
    restart: always
    container_name: nginx
    image: nginx
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/log:/var/log/nginx
